const SUPABASE_URL = "https://zywmgdwunvzvgsmiujlx.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5d21nZHd1bnZ6dmdzbWl1amx4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjAxNjIwMiwiZXhwIjoyMDkxNTkyMjAyfQ.FNFdvMdv3u54cd6RA8s23frs7rFpUVIS_6Q5bvLPTzs";

window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
